default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: bandsfinder_development

test:
  <<: *default
  database: bandsfinder_test

production:
  <<: *default
  database: bandsfinder_production
